import logging
log = logging.getLogger("yomo")

import random

class RandomSelecting:

    def __init__(self):
        self.movesets = {
            "ANNIE": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "6MP",
                "6HP",
                "THROW",
                "L CRESCENT CUT",
                "M CRESCENT CUT",
                "H CRESCENT CUT",
                "L NORTH KNUCKLE",
                "M NORTH KNUCKLE",
                "H NORTH KNUCKLE",
                "L DESTRUCTION PILLAR",
                "M DESTRUCTION PILLAR",
                "H DESTRUCTION PILLAR",
                "TAUNT",
                "DASH"
            ],
            "BEOWULF": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L HURTING HURL",
                "M HURTING HURL",
                "H HURTING HURL",
                "L WULF BLITZER",
                "M WULF BLITZER",
                "H WULF BLITZER",
                "WULF SHOOT",
                "TAUNT",
                "DASH"
            ],
            "BIG BAND": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "WEED BLASTER",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L BEAT EXTEND",
                "M BEAT EXTEND",
                "H BEAT EXTEND",
                "L BRASS KNUCKLES",
                "M BRASS KNUCKLES",
                "H BRASS KNUCKLES",
                "L A TRAIN",
                "M A TRAIN",
                "H A TRAIN",
                "L GIANT STEP",
                "M GIANT STEP",
                "H GIANT STEP",
                "TAUNT",
                "DASH"
            ],
            "BLACK DAHLIA": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "UNDER NIGHT IN-BIRTH ASSAULT REFERENCE",
                "L ORDER UP!",
                "M ORDER UP!",
                "H ORDER UP!",
                "L ANOTHER ROUND",
                "M ANOTHER ROUND",
                "H ANOTHER ROUND",
                "TEA TIME",
                "EMPOWER",
                "COUNTER, STRIKE!",
                "TAUNT",
                "DASH"
            ],
            "CEREBELLA": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "6HP",
                "THROW",
                "L LOCK N LOAD",
                "M LOCK N LOAD",
                "H LOCK N LOAD",
                "DEFLECTOR",
                "DEVIL HORNS",
                "CERECOPTER",
                "DIAMOND DROP",
                "MERRY GO RILLA",
                "EXCELLABELLA",
                "TUMBLING RUN",
                "RUN STOP",
                "KANCHOU",
                "BATTLE BUTT",
                "TAUNT",
                "DASH"
            ],
            "DOUBLE": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "FLESH STEP",
                "L LUGER",
                "M LUGER",
                "H LUGER",
                "L BOMBER",
                "M BOMBER",
                "H BOMBER",
                "CILIA SLIDE",
                "TAUNT",
                "DASH"
            ],
            "ELIZA": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L UPPER KHAT",
                "M UPPER KHAT",
                "H UPPER KHAT",
                "L OSIRIS SPIRAL",
                "M OSIRIS SPIRAL",
                "H OSIRIS SPIRAL",
                "THRONE OF ISIS",
                "DIVE OF HORUS",
                "WEIGHT OF ANUBIS",
                "KHOPESH",
                "BUTCHERS BLADE",
                "AXE",
                "TAUNT",
                "DASH"
            ],
            "FILIA": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L RINGLET SPIKE",
                "M RINGLET SPIKE",
                "H RINGLET SPIKE",
                "RINGLET PSYCHE",
                "L UPDO",
                "M UPDO",
                "H UPDO",
                "L HAIRBALL",
                "M HAIRBALL",
                "H HAIRBALL",
                "TAUNT",
                "DASH"
            ],
            "FUKUA": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "L DART",
                "M DART",
                "H DART",
                "L CLONE",
                "M CLONE",
                "H CLONE",
                "L DRILL",
                "M DRILL",
                "H DRILL",
                "TENDER EMBRACE",
                "INEVITABLE SNUGGLE",
                "TAUNT",
                "DASH"
            ],
            "MARIE": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "HOP TO IT",
                "MARIE GO ROUND L",
                "MARIE GO ROUND M",
                "MARIE GO ROUND H",
                "SUCTION OBSTRUCTION",
                "HILGARD'S HAYMAKER L",
                "HILGARD'S HAYMAKER M",
                "HILGARD'S HAYMAKER H",
                "HILGARD'S HOWL L",
                "HILGARD'S HOWL M",
                "HILGARD'S HOWL H",
                "TAUNT",
                "DASH"
            ],
            "MS. FORTUNE": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L CAT SCRATCH",
                "M CAT SCRATCH",
                "H CAT SCRATCH",
                "CAT STRIKE",
                "L FIBER",
                "M FIBER",
                "H FIBER",
                "TAUNT",
                "DASH"
            ],
            "PAINWHEEL": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "6HK",
                "FLIGHT",
                "L STINGER",
                "M STINGER",
                "H STINGER",
                "L BUER",
                "M BUER",
                "H BUER",
                "L PINION",
                "M PINION",
                "H PINION",
                "TAUNT",
                "DASH"
            ],
            "PARASOUL": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "6LP",
                "6MP",
                "6HP",
                "4HK",
                "L NAPALM TOSS",
                "M NAPALM TOSS",
                "H NAPALM TOSS",
                "L NAPALM SHOT",
                "M NAPALM SHOT",
                "H NAPALM SHOT",
                "NAPALM TRIGGER",
                "NAPALM QUAKE",
                "NAPALM PILLAR",
                "EGRET CALL",
                "EGRET DIVE",
                "EGRET CHARGE",
                "TAUNT",
                "DASH"
            ],
            "PEACOCK": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L BANG",
                "M BANG",
                "H BANG",
                "L GEORGE",
                "M GEORGE",
                "H GEORGE",
                "L ITEM DROP",
                "M ITEM DROP",
                "H ITEM DROP",
                "CHARGED L ITEM DROP",
                "CHARGED M ITEM DROP",
                "CHARGED H ITEM DROP",
                "L TELEPORT",
                "M TELEPORT",
                "H TELEPORT",
                "TAUNT",
                "DASH"
            ],
            "ROBO-FORTUNE": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L BEAM",
                "M BEAM",
                "H BEAM",
                "RAM",
                "MINE",
                "SALVO",
                "L DANGER",
                "M DANGER",
                "H DANGER",
                "TAUNT",
                "DASH"
            ],
            "SQUIGLY": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "6HP",
                "THROW",
                "LIVER MORTIS",
                "CENTER STAGE",
                "DRAG N BITE",
                "DRAUGEN PUNCH",
                "ARPEGGIO",
                "THE SILVER CHORD",
                "TREMOLO",
                "TAUNT",
                "DASH"
            ],
            "UMBRELLA": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "6LP",
                "6HP",
                "TONGUE TWISTER",
                "SALT GRINDER",
                "SLURP 'N' SLIDE",
                "HUNGERN RUSH",
                "CUTIE PTOOIE",
                "BOBBLIN' BUBBLE",
                "WISH MAKER",
                "TAUNT",
                "DASH"
            ],
            "VALENTINE": 
            [
                "5LP",
                "5MP",
                "5HP",
                "5LK",
                "5MK",
                "5HK",
                "2LP",
                "2MP",
                "2HP",
                "2LK",
                "2MK",
                "2HK",
                "THROW",
                "L DEAD CROSS",
                "M DEAD CROSS",
                "H DEAD CROSS",
                "L BYPASS",
                "M BYPASS",
                "H BYPASS",
                "L VIAL HAZARD",
                "M VIAL HAZARD",
                "H VIAL HAZARD",
                "FLEW SHOT",
                "MORTUARY DROP",
                "TAUNT",
                "DASH"
            ],
        }

    # pick and format random team
    def random_team(self):
        team = random.sample(self.movesets.keys(), 3)
        return '\n'.join([
            f"Point: {self.character_string(team[0])}",
            f"Mid: {self.character_string(team[1])}",
            f"Anchor: {self.character_string(team[2])}"
        ])

    # pick and format a random assist
    def character_string(self, character):
        assist = random.choice(self.movesets[character])
        return f"**{character}** ({assist} assist)"
